[workspace]
resolver = "2"

members = [
    "interact-gas",

    "paint-harvest-sc",
    "paint-harvest-sc/meta",

    "paint-the-moon-sc",
    "paint-the-moon-sc/meta",

    "tools/img-processing",
    # "tools/moon-plotter",
    "tools/sphere",
]
