[settings]
main = "main"

[contracts.main]
name = "paint-the-moon-main"

[contracts.block8]
name = "paint-the-moon-8"
features = ["block-size", "block-size-8"]

[contracts.block16]
name = "paint-the-moon-16"
features = ["block-size", "block-size-16"]

[contracts.block32]
name = "paint-the-moon-32"
features = ["block-size", "block-size-32"]

[contracts.block64]
name = "paint-the-moon-64"
features = ["block-size", "block-size-64"]
