chain_type = 'simulator'
gateway_uri = 'http://localhost:8085'
moon_address = 'erd1qqqqqqqqqqqqqpgqj9uy4yg3fu67362rmth3ylgd5km8fej3wadsm4fvtk'

# chain_type = 'real'
# gateway_uri = 'https://devnet-gateway.multiversx.com'

