[package]
name = "paint-the-moon-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
multiversx-sc-meta-lib = { git = "https://github.com/multiversx/mx-sdk-rs/", rev = "2d18801187a5ea89949647f07553ed80e695dab5", default-features = false }
paint-the-moon-sc = { path = ".." }
