[package]
name = "paint-harvest-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.paint-harvest-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "fd6a6c862576b18359e65918b4e84068f11ace44"
