[package]
name = "paint-harvest-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
multiversx-sc-meta-lib = { git = "https://github.com/multiversx/mx-sdk-rs/", rev = "3a0c91737ef73c133c9aa95b690eba9909cb6063", default-features = false }
paint-harvest-sc = { path = ".." }
