[package]
name = "paint-harvest-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.paint-harvest-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.3"
default-features = false
