[package]
name = "common"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8.19" }
multiversx-sc = { git = "https://github.com/multiversx/mx-sdk-rs/", rev = "2d18801187a5ea89949647f07553ed80e695dab5" }
multiversx-sc-snippets-dapp = { git = "https://github.com/multiversx/mx-sdk-rs/", rev = "2d18801187a5ea89949647f07553ed80e695dab5" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.70", features = ["Window"] }
gloo-net = { version = "0.6.0", features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actix-web = "4.9.0"
redis = { version = "0.27.0", features = ["async-std-comp"] }
serde_json = "1.0.128"
