[package]
name = "common-wasm"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8.19" }
